# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='corp_card_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='Корпоративная карта скан'),
        ),
        migrations.AlterField(
            model_name='car',
            name='diag_card_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='Диагн. карта скан'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_card_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='Топливная карта скан'),
        ),
        migrations.AlterField(
            model_name='car',
            name='kasko_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='КАСКО скан'),
        ),
        migrations.AlterField(
            model_name='car',
            name='osago_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='ОСАГО скан'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pts_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='ПТС скан'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sts_scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='СТС скан'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='key',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/keycards/', verbose_name='Скан'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/penalties/', verbose_name='Скан'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/proxies/', verbose_name='Скан'),
        ),
    ]
