# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('td', '0002_auto_20170127_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата передачи')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee', verbose_name='Кому выдана')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Proxy', verbose_name='Доверенность')),
            ],
            options={
                'verbose_name': 'Выдача доверенности',
                'verbose_name_plural': 'Выдачи доверенностей',
            },
        ),
    ]
