# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('td', '0003_proxytracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pts', 'ПТС'), ('sts', 'СТС'), ('diag_card', 'Диагностическая карта'), ('fuel_card', 'Топливная карта'), ('corp_card', 'Корпоративная карта'), ('osago', 'Полис ОСАГО'), ('kasko', 'Полис КАСКО'), ('key-car', 'Ключ от автомобиля'), ('key-alarm', 'Ключ от сигнализации'), ('key-card', 'Ключ-карта'), ('key-parking', 'Пропуск на парковку')], max_length=50, verbose_name='Тип ключа')),
                ('number', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Номер')),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Пин код')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('company', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Компания')),
                ('comment', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Комментарий')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('scan', models.FileField(blank=True, null=True, upload_to='scans/documents/', verbose_name='Скан')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='ItemTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата передачи')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Proxy', verbose_name='Доверенность')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee', verbose_name='Кому выдана')),
            ],
            options={
                'verbose_name': 'Выдача документов/ключей',
                'verbose_name_plural': 'Выдачи документов/ключей',
            },
        ),
        migrations.RemoveField(
            model_name='key',
            name='car',
        ),
        migrations.RemoveField(
            model_name='key',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='corp_card_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='corp_card_pin',
        ),
        migrations.RemoveField(
            model_name='car',
            name='corp_card_place',
        ),
        migrations.RemoveField(
            model_name='car',
            name='corp_card_scan',
        ),
        migrations.RemoveField(
            model_name='car',
            name='diag_card_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='diag_card_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='diag_card_place',
        ),
        migrations.RemoveField(
            model_name='car',
            name='diag_card_scan',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_card_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_card_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_card_pin',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_card_place',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_card_scan',
        ),
        migrations.RemoveField(
            model_name='car',
            name='kasko_company',
        ),
        migrations.RemoveField(
            model_name='car',
            name='kasko_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='kasko_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='kasko_place',
        ),
        migrations.RemoveField(
            model_name='car',
            name='kasko_scan',
        ),
        migrations.RemoveField(
            model_name='car',
            name='osago_company',
        ),
        migrations.RemoveField(
            model_name='car',
            name='osago_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='osago_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='osago_place',
        ),
        migrations.RemoveField(
            model_name='car',
            name='osago_scan',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pts_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pts_place',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pts_scan',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sts_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sts_place',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sts_scan',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.AddField(
            model_name='item',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='td.Car', verbose_name='Автомобиль'),
        ),
    ]
