# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0004_auto_20170207_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtracking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Item', verbose_name='Доверенность'),
        ),
        migrations.AlterField(
            model_name='itemtracking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Driver', verbose_name='Кому выдана'),
        ),
        migrations.AlterField(
            model_name='proxytracking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Driver', verbose_name='Кому выдана'),
        ),
    ]
