# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0005_auto_20170207_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Документ/ключ/пропуск', 'verbose_name_plural': 'Документы/ключи/пропуска'},
        ),
        migrations.AlterField(
            model_name='item',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='item',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='scans/car_items/', verbose_name='Скан'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('pts', 'ПТС'), ('sts', 'СТС'), ('diag_card', 'Диагностическая карта'), ('fuel_card', 'Топливная карта'), ('corp_card', 'Корпоративная карта'), ('osago', 'Полис ОСАГО'), ('kasko', 'Полис КАСКО'), ('key-car', 'Ключ от автомобиля'), ('key-alarm', 'Ключ от сигнализации'), ('key-card', 'Ключ-карта'), ('key-parking', 'Пропуск на парковку')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='itemtracking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Item', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='itemtracking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Driver', verbose_name='Кому выдан'),
        ),
    ]
