# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0006_auto_20170209_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='to',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название'),
        ),
    ]
