# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0007_to_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Описание')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Комментарий')),
                ('scan', models.FileField(blank=True, null=True, upload_to='scans/accidents/', verbose_name='Скан')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Car', verbose_name='Автомобиль')),
                ('culprit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='td.Driver', verbose_name='Виновник')),
            ],
            options={
                'verbose_name_plural': 'ДТП',
                'verbose_name': 'ДТП',
            },
        ),
    ]
