# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0008_accident'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Описание')),
                ('scan', models.FileField(blank=True, null=True, upload_to='scans/accidents/', verbose_name='Скан')),
            ],
            options={
                'verbose_name_plural': 'документы ДТП',
                'verbose_name': 'документ ДТП',
            },
        ),
        migrations.RemoveField(
            model_name='accident',
            name='scan',
        ),
        migrations.AddField(
            model_name='accidentdoc',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td.Accident', verbose_name='ДТП'),
        ),
    ]
