# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0009_auto_20170228_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tires_summer_photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/tires/', verbose_name='Летние колеса, фото'),
        ),
        migrations.AddField(
            model_name='car',
            name='tires_winter_photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/tires/', verbose_name='Зимние колеса, фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tires_storage',
            field=models.CharField(blank=True, choices=[('0', ' '), ('1', 'Динамика М'), ('2', 'У водителя в гараже/дома'), ('3', 'ТРК Щука'), ('4', 'Стенд-авто')], default='0', max_length=1, null=True, verbose_name='Место хранения колес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('pts', 'ПТС'), ('sts', 'СТС'), ('diag_card', 'Диагностическая карта'), ('fuel_card', 'Топливная карта'), ('corp_card', 'Корпоративная карта'), ('service_book', 'Сервисная книжка'), ('osago', 'Полис ОСАГО'), ('kasko', 'Полис КАСКО'), ('key-car', 'Ключ от автомобиля'), ('key-alarm', 'Ключ от сигнализации'), ('key-card', 'Ключ-карта'), ('key-parking', 'Пропуск на парковку')], max_length=50, verbose_name='Тип'),
        ),
    ]
