# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0010_auto_20170228_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='scans/licenses/', verbose_name='Скан вод. удостоверения'),
        ),
    ]
