# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0011_auto_20170328_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to',
            old_name='budget',
            new_name='budget_amount',
        ),
        migrations.RemoveField(
            model_name='to',
            name='fact',
        ),
        migrations.AddField(
            model_name='to',
            name='fact_amount',
            field=models.FloatField(default=0, verbose_name='Факт. расходы'),
        ),
    ]
