# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0013_auto_20170607_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='gasoline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расходы на бензин'),
        ),
    ]
