# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0014_mileage_gasoline'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='basis',
            field=models.IntegerField(blank=True, choices=[(0, 'ДДА')], null=True, verbose_name='Основание'),
        ),
        migrations.AddField(
            model_name='parking',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Примечение'),
        ),
        migrations.AddField(
            model_name='parking',
            name='floor_number',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='parking',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Грейд'),
        ),
        migrations.AddField(
            model_name='visitorsparking',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Показания одометра'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(0, '100%'), (1, 'Субаренда')], null=True, verbose_name='Условия оплаты'),
        ),
        migrations.AlterField(
            model_name='visitorsparking',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время приезда'),
        ),
    ]
