# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0015_auto_20170705_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Показания одометра на конец месяца'),
        ),
    ]
