# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_department_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017, verbose_name='Год')),
                ('division', models.CharField(choices=[('GORN', 'ГОРН Девелопмент'), ('ZEL', 'Аппарат Зеленова')], default='GORN', max_length=10, verbose_name='Подразделение')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Договор')),
                ('number', models.CharField(max_length=20, verbose_name='Номер довогора')),
                ('group', models.CharField(max_length=5, verbose_name='Группа счетов')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены договора')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Изменение договора',
                'verbose_name_plural': 'Изменения договоров',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Лимит')),
                ('infinite', models.BooleanField(default=False, verbose_name='Безлимитный')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Начало периода')),
            ],
            options={
                'verbose_name': 'Лимит',
                'verbose_name_plural': 'Лимиты',
            },
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Номер')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'SIM-карта',
                'verbose_name_plural': 'SIM-карты',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание тарифа')),
                ('active', models.BooleanField(default=True, verbose_name='Актуальный')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date(2000, 1, 1), verbose_name='Дата передачи')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee', verbose_name='Сотрудник')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Sim', verbose_name='SIM-карта')),
            ],
            options={
                'verbose_name': 'Передача SIM-карты',
                'verbose_name_plural': 'Передачи SIM-карты',
            },
        ),
        migrations.AddField(
            model_name='sim',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Tariff', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='limit',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Sim', verbose_name='SIM-карта'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Sim', verbose_name='SIM-карта'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Sim', verbose_name='SIM-карта'),
        ),
    ]
