# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_division'),
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='current_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_sim', to='mobile.Limit', verbose_name='Текущий лимит'),
        ),
        migrations.AddField(
            model_name='sim',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Employee', verbose_name='Текущий владелец'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Дата передачи'),
        ),
    ]
