# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_auto_20170502_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='billfile',
            name='data',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
