# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_billfile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billfile',
            name='file',
            field=models.FileField(upload_to='uploads/mobile_bills', verbose_name='Файл'),
        ),
    ]
