# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import mobile.models.bill_file


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_auto_20170502_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billfile',
            name='file',
            field=models.FileField(upload_to=mobile.models.bill_file.file_path, verbose_name='Файл'),
        ),
    ]
