# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_auto_20170503_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billfile',
            name='data',
        ),
        migrations.AddField(
            model_name='bill',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Сверен'),
        ),
    ]
