# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0010_auto_20170503_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.Sim', verbose_name='SIM-карта'),
        ),
    ]
