# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0011_auto_20170503_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='checked',
        ),
        migrations.AddField(
            model_name='contract',
            name='mts',
            field=models.BooleanField(default=False, verbose_name='МТС'),
        ),
    ]
