# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mobile.models.bill_file


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0013_auto_20170503_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.Sim', verbose_name='SIM-карта'),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=mobile.models.bill_file.file_path, verbose_name='Файл'),
        ),
    ]
