# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0014_auto_20170504_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='billfile',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
    ]
