# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0016_auto_20170505_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Сумма'),
        ),
    ]
