# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0017_auto_20170511_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
    ]
