# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0018_auto_20170511_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='month',
            field=models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=6, verbose_name='Месяц'),
        ),
    ]
