# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0020_auto_20170704_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billfile',
            name='month',
            field=models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=8, verbose_name='Месяц'),
        ),
    ]
