# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import service.models.checklist_value


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_contact_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обхода')),
                ('state', models.CharField(choices=[['new', 'Новый'], ['ok', 'Замечаний нет'], ['has_issues', 'Есть замечания'], ['issues_solved', 'Замечания устранены']], max_length=20, verbose_name='Статус')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='ChecklistRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ord_number', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Строка отчета',
                'ordering': ['zone', 'ord_number'],
                'verbose_name_plural': 'Строки отчета',
            },
        ),
        migrations.CreateModel(
            name='ChecklistValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_issues', models.BooleanField(default=False, verbose_name='Есть замечания')),
                ('solve_date', models.DateField(blank=True, null=True, verbose_name='Дата устранения')),
                ('photo', models.FileField(blank=True, null=True, upload_to=service.models.checklist_value.file_path, verbose_name='Фото')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Примечания')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Checklist', verbose_name='Отчет')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ChecklistRow', verbose_name='Строка отчета')),
            ],
            options={
                'verbose_name': 'Значение строки отчета',
                'verbose_name_plural': 'Значения строк отчета',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервиса')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Сервисный провайдер',
                'verbose_name_plural': 'Сервисные провайдеры',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('block', models.IntegerField(choices=[[0, 'Клининг'], [1, 'Техническая эксплуатация'], [2, 'Флористика']], verbose_name='Блок')),
                ('ord_number', models.IntegerField(default=0, verbose_name='Порядоковый номер')),
            ],
            options={
                'verbose_name': 'Зона',
                'ordering': ['block', 'ord_number'],
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.AddField(
            model_name='checklistrow',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Zone', verbose_name='Зона'),
        ),
    ]
