# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170726_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
        migrations.AddField(
            model_name='ticket',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
