# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170731_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Provider', verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Содержание'),
        ),
    ]
