# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import service.models.ticket


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20170804_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=service.models.ticket.file_path, verbose_name='Фото'),
        ),
    ]
