# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.CharField(blank=True, choices=[('GORN', 'ГОРН Девелопмент'), ('ZEL', 'Аппарат Зеленова')], default='GORN', max_length=10, null=True, verbose_name='Подразделение'),
        ),
    ]
