# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Группы сотрудников',
                'ordering': ['name'],
                'verbose_name': 'Группа сотрудников',
            },
        ),
    ]
