# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name='Группа'),
        ),
    ]
