# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('value', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
            },
        ),
    ]
